version: 1.1.{build}
branches:
  except:
  - gh-pages
skip_tags: true
image: Visual Studio 2017
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
build_script:
- cmd: dotnet pack -o output -c Release --include-symbols --include-source CommandDotNet.IoC.Autofac.csproj /p:Version=%APPVEYOR_BUILD_VERSION%
test_script:
- cmd: dotnet test Tests/Tests.csproj
artifacts:
- path: output/**
  name: Nuget
deploy:
- provider: NuGet
  api_key:
    secure: 5IPw0XSONngrDba05Y63BmRAU/vz/ACR1Hzd74soIr9ZB7Z/Epl6+7wBYZ9ihDeO
  skip_symbols: false
  artifact: Nuget
  on:
    branch: release
- provider: GitHub
  auth_token:
    secure: CYhAEm/f6dhXf8d5F46G8YTfgHnU7UFVCJUknwIbNZzK06XHNHSIaPmZ+VeV4Afx
  on:
    branch: release
notifications:
- provider: Email
  to:
  - bilal.m.fazlani@gmail.com
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true